// Starter content. After the first load, posts live in localStorage.
export const CATEGORIES = ['Tech', 'Design', 'Career', 'Life']

export const seed = [
  {
    id: 'p1',
    title: 'Why I stopped reaching for useEffect first',
    category: 'Tech',
    author: 'Aarav Mehta',
    date: '2026-09-28',
    likes: 14,
    body: "For a long time, every piece of logic in my components ended up inside an effect. Fetch some data, sync some state, update the title. It worked, but the components were hard to read.\n\nNow I ask one question first: can this value be calculated during render? If a value comes from props or state, it usually can. Filtering a list, formatting a date or counting items are all plain expressions.\n\nEffects are still useful for talking to things outside React, like timers, subscriptions and the browser. Keeping them for that job made my code shorter and easier to debug.",
    comments: [{ id: 'c1', name: 'Riya', text: 'This matches what I ran into last month. Derived state saved me a lot of bugs.', date: '2026-09-29' }],
  },
  {
    id: 'p2',
    title: 'A simple way to pick a colour palette',
    category: 'Design',
    author: 'Sana Qureshi',
    date: '2026-09-21',
    likes: 9,
    body: "Start with one neutral and one accent. That's it. Most interfaces need far fewer colours than we think.\n\nPick a background and a text colour with enough contrast, then choose a single accent for links and buttons. Add success and error colours only when you actually need them.\n\nTest the palette in both light and dark mode early. Fixing contrast at the end is much more painful.",
    comments: [],
  },
  {
    id: 'p3',
    title: 'Preparing for your first technical interview',
    category: 'Career',
    author: 'Kabir Singh',
    date: '2026-09-15',
    likes: 22,
    body: "Nobody expects you to know everything. Interviewers mostly want to see how you think when you get stuck.\n\nTalk through your approach out loud. Start with a simple solution, then improve it. If you don't know something, say so and explain how you would find out.\n\nPractise with a friend if you can. Explaining your thinking to a real person is a different skill from solving problems alone.",
    comments: [],
  },
  {
    id: 'p4',
    title: 'Building a reading habit that lasts',
    category: 'Life',
    author: 'Meera Nair',
    date: '2026-09-08',
    likes: 6,
    body: "I used to set big goals like a book a week and give up after ten days. What worked instead was reading for ten minutes before bed.\n\nKeep the book where you'll see it. Put your phone in another room. Stop when the ten minutes are up, even if you want to continue, so tomorrow feels easy to start.\n\nAfter a month it stopped feeling like a goal and became part of the evening.",
    comments: [],
  },
  {
    id: 'p5',
    title: 'CSS Grid layouts without the headache',
    category: 'Tech',
    author: 'Aarav Mehta',
    date: '2026-08-30',
    likes: 11,
    body: "Most card layouts need just one line: grid-template-columns with repeat, auto-fill and minmax. The browser works out how many columns fit.\n\nThis removes most media queries for simple pages. Add a gap, set a minimum card width, and the layout adapts from phone to desktop by itself.\n\nReach for explicit breakpoints only when the design really changes between sizes.",
    comments: [],
  },
  {
    id: 'p6',
    title: 'Writing documentation people actually read',
    category: 'Career',
    author: 'Sana Qureshi',
    date: '2026-08-19',
    likes: 4,
    body: "Good documentation answers the question the reader came with. Put setup steps first, then examples, then the details.\n\nShort sentences help. So do real examples that can be copied and run. If a step can fail, say what the error looks like and how to fix it.\n\nRead your own README as if you've never seen the project. You'll find the gaps quickly.",
    comments: [],
  },
]
